name: CD

on:
  push:
    branches:
      - $default_branch
  release:
    types:
      - created
  workflow_dispatch:
#  pull_request:
# uncoment the line above to test CD push in a PR

jobs:
  call-external:
     uses: jina-ai/workflows-executors/.github/workflows/cd.yml@master
     with:
       event_name: ${{ github.event_name }}
     secrets:
       secret: ${{ secrets.SECRET }}